# Generated by Django 5.2.4 on 2025-07-24 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_addproducts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='colour',
        ),
        migrations.AddField(
            model_name='addproducts',
            name='brand',
            field=models.CharField(blank=True, choices=[('Nike', 'Nike'), ('Adidas', 'Adidas'), ('Puma', 'Puma'), ('Reebok', 'Reebok')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='addproducts',
            name='colour',
            field=models.CharField(blank=True, default='Black', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='addproducts',
            name='size',
            field=models.CharField(blank=True, choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], max_length=10, null=True),
        ),
    ]
